export const Media = [
    { type: 'image', url: require('./3D/Bricks.jpeg'), category: '3D' },
    { type: 'video', url: require('./3D/bm.mp4'), category: '3D' },
    { type: 'image', url: require('./3D/DopedCard.jpeg'), category: '3D' },
    { type: 'video', url: require('./3D/marchii.mp4'), category: '3D' },
    { type: 'video', url: require('./3D/archipres.mp4'), category: '3D' },
    { type: 'image', url: require('./SHOOTING/SHOT 1.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 2.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 3.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 4.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 5.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN 2.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN 3.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 6.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 7.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 8.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 9.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./MOVENPICK/AB.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07878.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07887.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07925.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07926.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07928.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07934.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07937.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07941.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07943.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07955.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7456.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7464.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7466.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7468.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7474.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7478.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7484.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7492.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7497.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7504.webp'), category: 'MOVENPICK' },
    { type: 'image', url: require('./ALMO9AWALA/1.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/2.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/3.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/5.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/6.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/7.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/8.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/9.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/10.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/11.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/12.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/13.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/14.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/15.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/16.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/17.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/18.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/19.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/20.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/21.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/22.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/23.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/24.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/25.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/26.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/27.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/28.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/29.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/30.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/31.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/32.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./CONTENTCREATION/1.png'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/2.png'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/3.png'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/4.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/5.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/6.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/7.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/8.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/9.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/10.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/11.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/20.jpeg'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/21.png'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/22.png'), category: 'CONTENT' },
    { type: 'image', url: require('./CONTENTCREATION/23.png'), category: 'CONTENT' },
    { type: 'image', url: require('./DESIGN/ADE CARD.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/Copie de banderole.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/Copie de cover linkedin almou9awil.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/WhatsApp Image 2022-08-01 at 1.29.30 PM.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/back abdo zehrawi.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/front abdo zehrawi.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/cover fb ade.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/cover fb almou9awil.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/cover fb polydev.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/démo carte visite.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/exemple 1 carte.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./DESIGN/pdc fb comdabel.webp'), category: 'DESIGN' },
    { type: 'image', url: require('./POLYDEV/1.jpeg'), category: 'POLYDEV' },
    { type: 'image', url: require('./POLYDEV/2.jpeg'), category: 'POLYDEV' },
    { type: 'image', url: require('./POLYDEV/3.jpeg'), category: 'POLYDEV' },
    { type: 'image', url: require('./POLYDEV/cover fb polydev.webp'), category: 'POLYDEV' },
    { type: 'image', url: require('./ELKETANI/1.jpeg'), category: 'ELKETANI' },
    { type: 'image', url: require('./ELKETANI/2.png'), category: 'ELKETANI' },
    { type: 'image', url: require('./MO9AWIL/Copie de cover linkedin almou9awil.webp'), category: 'MO9AWIL' },
    { type: 'image', url: require('./MO9AWIL/cover fb almou9awil.webp'), category: 'MO9AWIL' },
    { type: 'video', url: require('./REELS/1.mp4'), category: 'REELS' },
    { type: 'video', url: require('./REELS/Medium Square-1.mp4'), category: 'REELS' },
    { type: 'video', url: require('./REELS/story exemple.mp4'), category: 'REELS' },

  ];
  
export const Logo = [
  { url: require('./LOGOS/Anatolia.png'), category: 'ANATOLIA' },
  { url: require('./LOGOS/DerouaPool.png'), category: 'DEROUA' },
  { url: require('./LOGOS/ElKetani.png'), category: 'ELKETANI' },
  { url: require('./LOGOS/GlitchAcademy.png'), category: 'GLITCHACADEMY' },
  { url: require('./LOGOS/HERITIMA.png'), category: 'HERITIMA' },
  { url: require('./LOGOS/LMO9AWALA.png'), category: 'ALMO9AWALA' },
  { url: require('./LOGOS/Mo9awil.png'), category: 'MO9AWIL' },
  { url: require('./LOGOS/Movenpick.png'), category: 'MOVENPICK' },
  { url: require('./LOGOS/NiceKoop.png'), category: 'NICEKOOP' },
  { url: require('./LOGOS/Poly.png'), category: 'POLYDEV' },
]