export const Media = [
    { type: 'image', url: require('./3D/Bricks.jpeg'), category: '3D' },
    { type: 'video', url: require('./3D/bm.mp4'), category: '3D' },
    { type: 'image', url: require('./3D/DopedCard.jpeg'), category: '3D' },
    { type: 'video', url: require('./3D/marchii.mp4'), category: '3D' },
    { type: 'video', url: require('./3D/archipres.mp4'), category: '3D' },
    { type: 'image', url: require('./SHOOTING/SHOT 1.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 2.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 3.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 4.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 5.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN 2.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN 3.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/TWIN.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 6.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 7.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 8.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./SHOOTING/SHOT 9.jpeg'), category: 'SHOOTING' },
    { type: 'image', url: require('./MOVENPICK/DSC07878.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07887.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07925.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07926.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07928.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07934.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07937.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07941.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07943.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/DSC07955.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./MOVENPICK/D_K_7456.jpg'), category: 'MOVENPICK' },
    { type: 'image', url: require('./ALMO9AWALA/1.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/2.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/3.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/5.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/6.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/7.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/8.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/9.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/10.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/11.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/12.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/13.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/14.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/15.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/16.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/17.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/18.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/19.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/20.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/21.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/22.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/23.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/24.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/25.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/26.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/27.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/28.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/29.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/30.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/31.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./ALMO9AWALA/32.jpeg'), category: 'ALMO9AWALA' },
    { type: 'image', url: require('./CONTENTCREATION/1.png'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/2.png'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/3.png'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/4.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/5.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/6.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/7.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/8.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/9.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/10.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/11.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/20.jpeg'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/21.png'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/22.png'), category: 'CONTENT CREATION' },
    { type: 'image', url: require('./CONTENTCREATION/23.png'), category: 'CONTENT CREATION' },


  ];
  
export const Logo = [
  { url: require('./LOGOS/Anatolia.png'), category: 'ANATOLIA' },
  { url: require('./LOGOS/DerouaPool.png'), category: 'DEROUA' },
  { url: require('./LOGOS/ElKetani.png'), category: 'ELKETANI' },
  { url: require('./LOGOS/GlitchAcademy.png'), category: 'GLITCHACADEMY' },
  { url: require('./LOGOS/HERITIMA.png'), category: 'HERITIMA' },
  { url: require('./LOGOS/LMO9AWALA.png'), category: 'ALMO9AWALA' },
  { url: require('./LOGOS/Mo9awil.png'), category: 'MO9AWIL' },
  { url: require('./LOGOS/Movenpick.png'), category: 'MOVENPICK' },
  { url: require('./LOGOS/NiceKoop.png'), category: 'NICEKOOP' },
  { url: require('./LOGOS/Poly.png'), category: 'POLYDEV' },
]